### ISSUE TITLE
Private/Internal fields that are not written to should be marked readonly

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/codeformatter#104]
Annotating fields as readonly if they’re internal/private and we can prove they’re only ever read from, aren’t mutating structs, etc.  There are potentially lots of fields across the codebase that could be made readonly, and while that doesn’t currently help with performance, it’s very helpful for readability, hygiene, etc.

**Comment by CyrusNajmabadi** [comment]
Does this also handle fields that are MEF imported?  These should not be marked readonly as MEF will need to assign to them.

**Comment by ChadNedzlek** [comment]
It should (and now does).
