### ISSUE TITLE
Add support for F#

### ISSUE THREAD

**Issue by nojaf** [dotnet/codeformatter#269]
Maybe try to involve the people behind [fantomas](https://github.com/dungpa/fantomas).

**Comment by alexsorokoletov** [comment]
This thing is based on Roslyn, which is C#/VB compiler infrastructure. For F# I am pretty sure you would have to have a separate tool. Which later might be incorporated into codeformatter just to have one tool for any .NET solution.

**Comment by nojaf** [comment]
The F# team is doing an effort in https://github.com/Microsoft/visualfsharp/pull/3542.
