### ISSUE TITLE
Release ilmerged assembly

### ISSUE THREAD

**Issue by jaredpar** [dotnet/codeformatter#27]
Downloaded the most recent release today to format some code and noticed that the release ZIP is quite large.  It's roughly 1 exe and 15 dlls.  

Personally, and maybe I'm wrong here, I had envisioned the command line tool as this little light weight tool that could be passed around for formatting code.  That's easy with an exe and maybe 1-2 dlls but 15 is too much.  

I was wondering if we should Ilmerge the binaries before creating a github release.  Been a while since I tried this out but a quick local experiment worked great and produced a single exe file that I can pass around.  

Thoughts?

**Comment by kzu** [comment]
how about an ILRepack'ed version? :)
