### ISSUE TITLE
Support linux

### ISSUE THREAD

**Issue by ivanivanyuk1993** [dotnet/codeformatter#292]
There is nothing in documentation about running it on linux, which should be possible since net5

Please add linux support, or document how to run it on linux

**Comment by tiesmaster** [comment]
FWIW [This is not really a supported project anymore](https://github.com/dotnet/codeformatter/issues/267), it has been superseeded by [dotnet-format](https://github.com/dotnet/format), which is supported, and is running on .NET Core / .NET 5.

**Comment by ivanivanyuk1993** [comment]
> FWIW [This is not really a supported project anymore](https://github.com/dotnet/codeformatter/issues/267), it has been superseeded by [dotnet-format](https://github.com/dotnet/format), which is supported, and is running on .NET Core / .NET 5.

Ok, thanks for reply
