### ISSUE TITLE
v1.0.0-alpha release doesn't contain System.Collections.Immutable

### ISSUE THREAD

**Issue by davkean** [dotnet/codeformatter#45]
The release I downloaded from https://github.com/dotnet/codeformatter/releases/tag/v1.0.0-alpha, doesn't contain System.Collections.Immutable and hence crashes.

**Comment by davkean** [comment]
Side note, we've got a bug around this against the MSBuild team.

**Comment by jaredpar** [comment]
@davkean 

Is it something they indicated they will fix?  The behavior is actually really infectious and ends up affecting how Visual Studio projects generate reference entries in files.
