### ISSUE TITLE
Need a method to opt out of rules

### ISSUE THREAD

**Issue by jaredpar** [dotnet/codeformatter#49]
There needs to be a method to opt out of individual rules.  In general yes the code formatter should be consistent and apply all rules to the code base.  Reasonable exceptions do popup on occasion though.  For example:

- The compiler code base needs to have files on disk with unicode characters simply to prove that we can read them in successfully.
- A few legacy code bases can't change private field names due to binary serialization.

Today we turn these off by checking out the code and commenting out the rule in question.  Would be much better if there was just a switch for it.

**Comment by Priya91** [comment]
Is this a duplicate of #14 ?

**Comment by jaredpar** [comment]
Ha, yeah it is :smile:
