### ISSUE TITLE
Delegate invokes of renamed fields are not repaired with the new name

### ISSUE THREAD

**Issue by roncain** [dotnet/codeformatter#68]
If you have a field like this:
      private Action someAction;

It will be renamed to '_someAction', and all reads and writes to it are also repaired.
But anywhere that field is used as a delegate to invoke the action, the name is not repaired.
Example:
      this.someAction();
will not be repaired, causing compile errors

**Comment by jaredpar** [comment]
Thanks for reporting.

That is very strange.  I think that may be another artifact of us using the beta2 version of Roslyn.  Will add a test to verify.
