### ISSUE TITLE
Renamed fields are not repaired when referenced via a class instance

### ISSUE THREAD

**Issue by roncain** [dotnet/codeformatter#69]
If you have a class and field like this:

``` csharp
   public class MyClass {
       private bool myBool;
   }
```

It will be renamed _myBool, and all references it to it will be replaced correctly.
But when it is referenced via an instance of that class (inside the class), it is not renamed, leading to compiler error:

```
   private void SomeMethodInsideMyClass(MyClass mc) {
      if (mc.myBool)...
   }
```

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  This looks to be the following bug in Roslyn

> https://github.com/dotnet/roslyn/issues/157

The code formatter as currently released was using Roslyn beta2.  I just upgrade it to RC1 and this issue should be fixed now.  Going to add a regression test for it today to ensure it was fixed.
