### ISSUE TITLE
An #if false in a set of using statements that need to be relocated deletes all the code in the #if

### ISSUE THREAD

**Issue by roncain** [dotnet/codeformatter#71]
Consider code that looks like this:

``` csharp
namespace  foo {
#if FALSE_CONDITION
   using x;
   using y;
   public class MyClass() {}
#else
   using z;
   public class MyClass() {}
#endif
```

When CodeFormatter attempts to relocate the using statements above the namespace, it deletes everything inside the #if FALSE_CONDITION, including the #if and the #else.  This causes all the #if'ed code to be deleted and results in an unpaired #endif, causing a compiler error.

**Comment by jaredpar** [comment]
Thanks for reporting this issue!  I will get this looked at.
