### ISSUE TITLE
Add support for formatting C# that doesn't have a solution or project file.

### ISSUE THREAD

**Issue by dannyvv** [dotnet/codeformatter#89]
Having a solution or msbuild project should not be a requirement for being able to run the codeformatter.

In other words: instead of passing: 
    <project or solution> 
to the tool someone should be able to alternatively pass:
    [/r:<reference>] [/cs:<sourcefile>]

The workspace that interanlly gets created would then not be an MsBuildWorkspace, but an AdHocWorkspace that is populated with a single project that contains the references and sources.

**Comment by ellismg** [comment]
Seems like a fine addition to me.  You'll also want to be able to pass define flags.  @dannyvv are you interested in doing the work and submitting a PR?

**Comment by dannyvv** [comment]
I'll go with an rsp file and do the work..
