### ISSUE TITLE
JSON configuration because JSON is new XML

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/codeformatter#98]
It would be really awesome if JSON-serialized config is provided instead of (<del>or in addition to</del>) XML.
Because JSON is simply so neat and XML is so *old century*, unnecessarily verbose, loaded and ugly! 

*JSON everywhere, for every data representation!*

**Comment by jaredpar** [comment]
To my knowledge there is no XML configuration here.  The only config file added to my knowledge was done by https://github.com/dotnet/codeformatter/commit/05039a8c1a730ce53e9ecabfc22d3ae98a14f834 and that uses the C# / VB RSP file format which is not XML.
